### ISSUE TITLE
US02 Authentification - Nouvel utilisateur

### ISSUE THREAD

**Issue by Gaelleb22** [Gaelleb22/carnet-front#15]
En tant que nouvel utilisateur, je veux pouvoir créer un nouvel utilisateur.

## Todo
- [ ] Lors de la création d'un nouvel utilisateur, celui-ci doit remplir un formulaire pour choisir un nom/pseudo et un mot de passe 
- [ ] Le mot de passe doit comporter de 6 à 12 caractères
- [ ] Le mot de passe doit être entré une deuxième fois et être le même que la première fois pour être accepté
